name: Build samples

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  packages: write

jobs:
  # Build job
  build:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Setup Go
        uses: actions/setup-go@v5
      - name: Set up Rust
        run: rustup update stable && rustup default stable
      - uses: lukka/get-cmake@latest
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11.6
        with:
          vcpkgGitCommitId: "9e593bb18ea69cc5095e012465dcd675a822ed0d" # https://github.com/microsoft/vcpkg/tree/2026.07.29
      - run: ./measure.ps1
